/**
 * Emits the VEFF effort-field fixture the frontend parser is tested against, so
 * the wire format stays in sync across the worker<->frontend boundary (the same
 * role make_golden plays for graph.bin). Writing is idempotent; the assertions
 * double as a round-trip check of the serializer.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

import { parseEffortFieldResponse, serializeEffortField } from '../src/protocol.js';
import { effortField, timeModel } from '../src/router.js';
import { loadRidgeWorld } from './fixtures.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURE_DIR = join(HERE, '..', '..', 'frontend', 'test', 'fixtures');

describe('frontend VEFF fixture', () => {
  it('emits effort-sample.bin + .json and round-trips', () => {
    const graph = loadRidgeWorld();
    const source = 100;
    const model = timeModel(7.5, 0.19444444444444445); // mixed profile
    const field = effortField(graph, source, model, { maxCost: 100_000 });
    const buffer = serializeEffortField(graph, source, field);

    const parsed = parseEffortFieldResponse(buffer);
    expect(parsed.count).toBe(field.count);
    expect(parsed.snappedNode).toBe(source);

    const sample = {
      note: 'Generated by worker/test/frontend-fixture.test.ts from the Ridge-World graph.',
      count: parsed.count,
      snappedNode: parsed.snappedNode,
      snappedLat: parsed.snappedLat,
      snappedLon: parsed.snappedLon,
      maxTime: parsed.maxTime,
      maxCumAscent: parsed.maxCumAscent,
      // A few entries for the frontend parser to assert against, by edge_id.
      entries: [0, 1, 2, 3, 4].map((i) => ({
        edgeId: parsed.edgeIds[i],
        time: parsed.times[i],
        cumAscent: parsed.cumAscents[i],
      })),
    };

    mkdirSync(FIXTURE_DIR, { recursive: true });
    writeFileSync(join(FIXTURE_DIR, 'effort-sample.bin'), Buffer.from(buffer));
    writeFileSync(join(FIXTURE_DIR, 'effort-sample.json'), JSON.stringify(sample, null, 2) + '\n');
  });
});
